### PR TITLE
Replace home grown TextReader with usage of encoding_rs_io crate

### LINKED ISSUE #32: Response.text panics when using charsets feature
When the `charsets` feature is enabled, `Response.text` panics in this program:

```
fn main() -> Result<(), attohttpc::Error> {
    let resp = attohttpc::get("https://rust-lang.org/").send()?;
    println!("{}", resp.text()?); // panic here
    Ok(())
}
```

The panic does not occur if the `charsets` feature is disabled, or if `Response.text_utf8` is used instead.

Version:
```
attohttpc = {"version" = "0.8.0", "features" = ["charsets"]}
```

Backtrace:
```
thread 'main' panicked at 'slice index starts at 12288 but ends at 8192', src/libcore/slice/mod.rs:2670:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  12: rust_begin_unwind
             at src/libstd/panicking.rs:302
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:139
  14: core::slice::slice_index_order_fail
             at src/libcore/slice/mod.rs:2670
  15: <core::ops::range::Range<usize> as core::slice::SliceIndex<[T]>>::index_mut
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/slice/mod.rs:2857
  16: <core::ops::range::RangeFrom<usize> as core::slice::SliceIndex<[T]>>::index_mut
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/slice/mod.rs:2933
  17: core::slice::<impl core::ops::index::IndexMut<I> for [T]>::index_mut
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/slice/mod.rs:2657
  18: <alloc::vec::Vec<T> as core::ops::index::IndexMut<I>>::index_mut
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/liballoc/vec.rs:1873
  19: std::io::read_to_end_with_reservation
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/io/mod.rs:389
  20: std::io::read_to_end
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/io/mod.rs:356
  21: std::io::Read::read_to_string::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/io/mod.rs:713
  22: std::io::append_to_string
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/io/mod.rs:333
  23: std::io::Read::read_to_string
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/io/mod.rs:713
  24: attohttpc::parsing::response_reader::ResponseReader::text_with
             at /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/attohttpc-0.8.0/src/parsing/response_reader.rs:129
  25: attohttpc::parsing::response_reader::ResponseReader::text
             at /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/attohttpc-0.8.0/src/parsing/response_reader.rs:117
  26: attohttpc::parsing::response::Response::text
             at /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/attohttpc-0.8.0/src/parsing/response.rs:143
  27: attohttpc_example::main
             at src/main.rs:3
  28: std::rt::lang_start::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  29: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:48
  30: std::panicking::try::do_call
             at src/libstd/panicking.rs:287
  31: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  32: std::panicking::try
             at src/libstd/panicking.rs:265
  33: std::panic::catch_unwind
             at src/libstd/panic.rs:396
  34: std::rt::lang_start_internal
             at src/libstd/rt.rs:47
  35: std::rt::lang_start
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  36: main
  37: __libc_start_main
  38: _start
```

### PR DESCRIPTION
**Pull request by adamreichold**
Considering the dependency is behind a feature and adds little code on top of encoding_rs, it seems reasonable to avoid the duplication. (And rather collaborate upstream if we need modifications to `DecodeBytesReader`.)

Closes #32

### CODE REVIEW

**Comment by sbstp** [comment]
I was not aware of the existence of this crate. This is definitely the way to go. The less code the better. And I would trust BurntSushi with my life.

File: src/parsing/response.rs [hunk 1]
```diff
@@ -156,26 +156,26 @@ impl Response {
...
+    /// Create a text reader from this `ResponseReader`.
     ///
     /// If the response headers contain charset information, that charset will be used to decode the body.
     /// Otherwise, if a default encoding is set it will be used. If there is no default encoding, ISO-8859-1
     /// will be used.
     ///
     /// This method only exists when the `charsets` feature is enabled.
     #[cfg(feature = "charsets")]
-    pub fn text_reader(self) -> TextReader<BufReader<ResponseReader>> {
+    pub fn text_reader(self) -> impl Read {
```
Comment (sbstp) [inline src/parsing/response.rs]: I'm not a fan or returning `impl Read`. I'd like to return a `TextReader` that implements `Read` to we can add methods on it in the future if necessary.

File: src/parsing/text_reader.rs [hunk 2]
```diff
@@ -1,135 +0,0 @@
...
-    let mut reader = TextReader::new(&b"qu\xC9bec"[..], crate::charsets::WINDOWS_1252);
-
-    let mut text = String::new();
-    assert_eq!(reader.read_to_string(&mut text).ok(), Some(7));
-
-    assert_eq!(text, "quÉbec");
-}
-
-#[test]
-fn test_string_reader_large_buffer_latin1() {
```
Comment (sbstp) [inline src/parsing/text_reader.rs]: Can you leave this test in just to make sure it really does what we want?

Comment (sbstp) [reply src/parsing/text_reader.rs]: Also this test was buggy, it did not assert that the length read to the string was at least 10,000 which would have caught the bug earlier on.

File: src/parsing/response.rs (hunk 1 above)
Comment (adamreichold) [reply src/parsing/response.rs]: Will add back `TextReader` as a wrapper around `DecodeBytesReader`.

File: src/parsing/text_reader.rs (hunk 2 above)
Comment (adamreichold) [reply src/parsing/text_reader.rs]: Will do when I add back a `TextReader` type.

File: src/parsing/response.rs (hunk 1 above)
Comment (adamreichold) [reply src/parsing/response.rs]: Done.

File: src/parsing/text_reader.rs (hunk 2 above)
Comment (adamreichold) [reply src/parsing/text_reader.rs]: Done.

**Comment by sbstp** [comment]
Thanks! It's out in `0.9.0`.
