### PR TITLE
RFC: Handle line-folded headers

### LINKED ISSUE #94: "InvalidResponse: invalid header" error on some websites
On some websites, e.g. http://opentrainer.ru, attohttpc fails with the following error:

> InvalidResponse: invalid header

Firefox and curl work fine.

32 websites out of the top million from [Feb 3 Tranco list](https://tranco-list.eu/list/3G6L) are affected.

Tested using [this code](https://github.com/Shnatsel/rust-http-clients-smoke-test/blob/main/attohttpc-smoke-test/src/main.rs). Test tool output from all affected websites: [atto-invalid-header.tar.gz](https://github.com/sbstp/attohttpc/files/5990836/atto-invalid-header.tar.gz)

### PR DESCRIPTION
**Pull request by adamreichold**
Split header lines only at CRLF boundary and replacing LF by SP in the resulting values.

Fixes #94

### CODE REVIEW

File: src/parsing/buffers.rs [hunk 1]
```diff
@@ -18,6 +18,28 @@ where
     Ok(n)
 }
 
+pub fn read_line_strict<R>(reader: &mut BufReader<R>, buf: &mut Vec<u8>, max_buf_len: u64) -> io::Result<usize>
```
Comment (sbstp) [inline src/parsing/buffers.rs:21]: Can you add a test below for this function?

Comment (sbstp) [reply src/parsing/buffers.rs:21]: Also maybe a test in this file as well https://github.com/sbstp/attohttpc/blob/master/src/parsing/response.rs#L21 to make sure it meshes well with an otherwise properly formatted response.

**Comment by sbstp** [comment]
I'm ok with merging this even if it's legacy stuff. The way you have found to implement it seems rather inexpensive (no alloc).

File: src/parsing/buffers.rs (hunk 1 above)
Comment (adamreichold) [reply src/parsing/buffers.rs:21]: Yes, I can do that. But I already found one issue with it: If the header contains CR that is not part of the line ending, the current code will fail, so I will probably have to refactor it considerably which will make it even more complicated. I am really not too enthused about it...

Comment (adamreichold) [reply src/parsing/buffers.rs:21]: Added tests here and there...

**Comment by sbstp** [comment]
Nice! You found a pretty clean way of handling this mess lol.
